# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "<Your Name>"
email                    : yuxuan.lin@connect.ust.hk
description              : MPhil
url                      : ""
baseurl                  : ""

# Site Author
author:
  name             : "Your Sidebar Name"
  avatar           : "pic.jpg"
  bio              : "Your biography for the left-hand sidebar"
  location         : "Location"
  googlescholar    : "http://yourfullgooglescholarurl.com"
  email            :
  researchgate     : "https://www.researchgate.net/profile/Yuxuan-Lin-4"
  facebook         :
  github           : "YuxuanSeanLin"
  orcid            : "https://orcid.org/0000-0002-5651-8816"
  twitter          : 
