# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "<Your Name>"
email                    : yuxuan.lin@connect.ust.hk
description              : MPhil
url                      : ""
baseurl                  : ""

# Site Author
author:
  name             : "Your Sidebar Name"
  avatar           : "pic.jpg"
  bio              : "Your biography for the left-hand sidebar"
  location         : "Location"
  googlescholar    : "http://yourfullgooglescholarurl.com"
  email            :
  researchgate     : "https://www.researchgate.net/profile/Yuxuan-Lin-4"
  facebook         :
  github           : "YuxuanSeanLin"
  orcid            : "https://orcid.org/0000-0002-5651-8816"
  twitter          : 

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Bryngelson
  first_name: [Spencer H.]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
